apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../10.Docker-compose_Terraform/docker-compose.yml convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {}
