apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../10.Docker-compose_Terraform/docker-compose.yml convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: sonarr
  name: sonarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sonarr
    spec:
      containers:
      - env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: Europe/London
        - name: UMASK
          value: "002"
        image: linuxserver/sonarr:latest
        name: sonarr
        ports:
        - containerPort: 8989
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: sonarr-claim0
        - mountPath: /tv
          name: sonarr-claim1
        - mountPath: /downloads
          name: sonarr-claim2
      restartPolicy: Always
      volumes:
      - name: sonarr-claim0
        persistentVolumeClaim:
          claimName: sonarr-claim0
      - name: sonarr-claim1
        persistentVolumeClaim:
          claimName: sonarr-claim1
      - name: sonarr-claim2
        persistentVolumeClaim:
          claimName: sonarr-claim2
status: {}
