apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../10.Docker-compose_Terraform/docker-compose.yml convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: sonarr
  name: sonarr
spec:
  ports:
  - name: "8989"
    port: 8989
    targetPort: 8989
  selector:
    io.kompose.service: sonarr
status:
  loadBalancer: {}
