Vagrant.configure("2") do |config|
    config.vm.define "centos_host" do |centos|
      centos.vm.box = "centos/stream8"
      centos.vm.box_version = "20210210.0"
      centos.vm.provider "virtualbox" do |vb|
            vb.gui = false
            vb.memory = "1024"
      end
      centos.vm.provision "shell", inline: <<-SHELL
        useradd updater -s /bin/bash
        echo "updater:vagrant" | chpasswd
        usermod -aG wheel updater
        touch /etc/sudoers.d/updater && \
        echo "%updater ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/updater
        yum install -y vim git wget curl
        # publish prep
        rm -rf /var/lib/apt/lists/*  /tmp/*  /var/tmp/* /usr/share/man /usr/share/doc /usr/share/doc-base
        cat /dev/null > ~/.bash_history && history -c && exit
      SHELL
    end
end
