Vagrant.configure("2") do |config|
    config.vm.define "host1" do |centos_1|
      centos_1.vm.box = "centos/7"
      centos_1.vm.network "private_network", ip: "192.168.100.1"
      centos_1.vm.provider "virtualbox" do |vb|
            vb.gui = false
            vb.memory = "512"
      end
      centos_1.vm.provision "shell", inline: <<-SHELL
        useradd admin -s /bin/bash
        echo "admin:admin" | chpasswd
        usermod -aG wheel admin
        touch /etc/sudoers.d/admin && \
        echo "%admin ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/admin
        yum install -y vim git wget curl nano
        cat /dev/null > ~/.bash_history && history -c && exit
      SHELL
    end
    config.vm.define "host2" do |centos_2|
        centos_2.vm.box = "centos/7"
        centos_2.vm.network "private_network", ip: "192.168.100.2"
        centos_2.vm.provider "virtualbox" do |vb|
              vb.gui = false
              vb.memory = "512"
        end
        centos_2.vm.provision "shell", inline: <<-SHELL
          useradd admin -s /bin/bash
          echo "admin:admin" | chpasswd
          usermod -aG wheel admin
          touch /etc/sudoers.d/admin && \
          echo "%admin ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/admin
          yum install -y vim git wget curl nano
          cat /dev/null > ~/.bash_history && history -c && exit
        SHELL
      end
end