Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "Jenkins"
    config.vm.network "public_network", ip: "192.168.100.100",  bridge: "enp3s0",
      use_dhcp_assigned_default_route: true ## TO CHANGE
    config.vm.provision :shell, :path => "bootstrap.sh"
end
