---
version: '3'

services:
  jenkins:
    image: jfrog.it-academy.by/public/jenkins-ci:spishchyk
    container_name: jenkins_ci_cd
    user: jenkins
    restart: always
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8081:8080"
