apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.service.name }}-pv
  labels:
    type: nfs
    name: app-nfs-vol
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /opt/nfs_share/wordpress_prod
    server: 172.24.172.144
