apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.service.name }}-claim0
  labels:
    app: {{ .Values.service.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      name: app-nfs-vol
      type: nfs