apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.service.name }}
  name: {{ .Values.service.name }}-service
  namespace: {{ .Values.service.namespace }}
spec:
  ports:
  - port: 8081
    targetPort: 80
    protocol: TCP
  selector:
    app: {{ .Values.service.name }}
