Vagrant.configure("2") do |config|
  config.vm.define "debian_host" do |debian|
    debian.vm.box = "debian/bullseye64"
    debian.vm.box_version = "11.20210409.1"
    debian.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "512"
    end
    debian.vm.provision "shell", inline: <<-SHELL
      useradd updater -s /bin/bash
      echo "updater:vagrant" | chpasswd
      usermod -aG sudo updater
      touch /etc/sudoers.d/updater && \
      echo "updater ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/updater
      apt-get update
      apt-get install -y vim git wget curl
      # publish prep
      rm -rf /var/lib/apt/lists/*  /tmp/*  /var/tmp/* /usr/share/man /usr/share/doc /usr/share/doc-base
      cat /dev/null > ~/.bash_history && history -c && exit
    SHELL
  end
end